import crypto from 'node:crypto';

export const PROVIDER_DEFINITIONS = [
  {
    id: 'gemini',
    label: 'Gemini',
    transport: 'gemini',
    defaultModel: 'gemini-2.5-flash',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com',
    envVar: 'GEMINI_API_KEY',
    requiresApiKey: true,
    local: false,
  },
  {
    id: 'openai',
    label: 'OpenAI',
    transport: 'openai-compatible',
    defaultModel: 'gpt-4.1-mini',
    defaultBaseUrl: 'https://api.openai.com/v1',
    envVar: 'OPENAI_API_KEY',
    requiresApiKey: true,
    local: false,
  },
  {
    id: 'anthropic',
    label: 'Anthropic',
    transport: 'anthropic',
    defaultModel: 'claude-3-5-sonnet-latest',
    defaultBaseUrl: 'https://api.anthropic.com',
    envVar: 'ANTHROPIC_API_KEY',
    requiresApiKey: true,
    local: false,
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    transport: 'openai-compatible',
    defaultModel: 'openai/gpt-4.1-mini',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    envVar: 'OPENROUTER_API_KEY',
    requiresApiKey: true,
    local: false,
  },
  {
    id: 'groq',
    label: 'Groq',
    transport: 'openai-compatible',
    defaultModel: 'llama-3.3-70b-versatile',
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    envVar: 'GROQ_API_KEY',
    requiresApiKey: true,
    local: false,
  },
  {
    id: 'mistral',
    label: 'Mistral',
    transport: 'openai-compatible',
    defaultModel: 'mistral-small-latest',
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    envVar: 'MISTRAL_API_KEY',
    requiresApiKey: true,
    local: false,
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    transport: 'openai-compatible',
    defaultModel: 'deepseek-chat',
    defaultBaseUrl: 'https://api.deepseek.com',
    envVar: 'DEEPSEEK_API_KEY',
    requiresApiKey: true,
    local: false,
  },
  {
    id: 'xai',
    label: 'xAI',
    transport: 'openai-compatible',
    defaultModel: 'grok-2-latest',
    defaultBaseUrl: 'https://api.x.ai/v1',
    envVar: 'XAI_API_KEY',
    requiresApiKey: true,
    local: false,
  },
  {
    id: 'lmstudio',
    label: 'LM Studio',
    transport: 'openai-compatible',
    defaultModel: 'local-model',
    defaultBaseUrl: 'http://localhost:1234/v1',
    envVar: '',
    requiresApiKey: false,
    local: true,
  },
  {
    id: 'ollama',
    label: 'Ollama',
    transport: 'ollama',
    defaultModel: 'llama3.2',
    defaultBaseUrl: 'http://localhost:11434',
    envVar: '',
    requiresApiKey: false,
    local: true,
  },
];

export const createDefaultProviderSettings = () =>
  Object.fromEntries(
    PROVIDER_DEFINITIONS.map(definition => [
      definition.id,
      {
        model: definition.defaultModel,
        baseUrl: definition.defaultBaseUrl,
        apiKey: '',
      },
    ])
  );

const createThreatIntelSources = () => ([
  {
    id: crypto.randomUUID(),
    name: 'Spamhaus DROP',
    url: 'https://www.spamhaus.org/drop/drop.txt',
    format: 'spamhaus_drop',
    enabled: true,
  },
  {
    id: crypto.randomUUID(),
    name: 'Spamhaus EDROP',
    url: 'https://www.spamhaus.org/drop/edrop.txt',
    format: 'spamhaus_drop',
    enabled: true,
  },
]);

export const createDefaultServerConfig = () => ({
  llmProvider: 'lmstudio',
  providerSettings: createDefaultProviderSettings(),
  deploymentMode: 'standalone',
  sensorId: 'desktop-lab-01',
  sensorName: 'Windows Lab Sensor',
  hubUrl: '',
  fleetSharedToken: '',
  globalBlockPropagationEnabled: false,
  captureInterface: '',
  captureFilter: 'ip and (tcp or udp)',
  cacheTtlSeconds: 60,
  batchWindowMs: 2000,
  batchMaxSize: 20,
  securePort: 9999,
  monitoringPorts: [22, 80, 443, 8080, 3389],
  detectionThreshold: 0.75,
  autoBlockThreats: false,
  liveRawFeedEnabled: false,
  firewallIntegrationEnabled: false,
  pcapBufferSize: 10,
  payloadMaskingMode: 'raw_local_only',
  sandboxEnabled: false,
  sandboxProvider: 'cape',
  sandboxBaseUrl: 'http://localhost:8090',
  sandboxApiKey: '',
  sandboxPollingIntervalMs: 5000,
  sandboxTimeoutSeconds: 300,
  sandboxAutoSubmitSuspicious: false,
  threatIntelEnabled: false,
  threatIntelRefreshHours: 24,
  threatIntelAutoBlock: false,
  threatIntelSources: createThreatIntelSources(),
  blockedIps: [],
  blockedPorts: [],
  exemptPorts: [],
  webhookIntegrations: [],
  customRules: [],
});
